# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  nerdFontsVersion: "3"
  sidePanelWidth: 0.2
git:
  overrideGpg: false
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: false
disableStartupPopups: true
os:
  editPreset: nvim-remote
# to skip without creating a new repo
notARepository: "skip"
confirmOnQuit: false
customCommands:
  - key: "<c-s>"
    command: "git rebase --exec 'git commit --amend --gpg-sign --no-edit' @~{{.Form.numberCommits}}"
    context: "commits"
    description: "GPGSign previous commits"
    prompts:
      - type: "input"
        title: "Number of commits to sign"
        key: numberCommits
        initialValue: "1"
