{{- /*
  vim:ft=toml.gotmpl:
*/ -}}

{{- if .osName | eq "ubuntu"  }}
[".local/bin/lazygit"]
  type = "archive-file"
  url = {{ gitHubLatestReleaseAssetURL "jesseduffield/lazygit" "lazygit_*_Linux_x86_64.tar.gz"  }}
  refresh = "168h"
  path = "lazygit"

[".local/bin/spf"]
  type = "archive-file"
  url = {{ gitHubLatestReleaseAssetURL "yorukot/superfile" (printf " superfile-%s-*-%s.tar.gz " .chezmoi.os .chezmoi.arch) }}
  refresh = "168h"
  path = "dist/**/spf"

[".local/bin/rbw"]
  type = "archive-file"
  url = {{ gitHubLatestReleaseAssetURL "doy/rbw" "rbw_*_linux_amd64.tar.gz" }}
  refresh = "168h"
  path = "rbw"

[".local/bin/rbw-agent"]
  type = "archive-file"
  url = {{ gitHubLatestReleaseAssetURL "doy/rbw" "rbw_*_linux_amd64.tar.gz" }}
  refresh = "168h"
  path = "rbw-agent"

[".local/bin/bob"]
  type = "archive-file"
  url = {{ gitHubLatestReleaseAssetURL "wintermi/zsh-bob" (printf "bob-%s-aarch64.zip" .chezmoi.os) }}
  refresh = "168h"
  path = "bob"
  format = "zip"
  filter.command = ["unzip"]

[".local/bin/eza"]
  type = "archive-file"
  url = {{ gitHubLatestReleaseAssetURL "eza-community/eza" " eza_x86_64-unknown-linux-gnu.tar.gz" }}
  refresh = "168h"
  path = "eza"

[".local/bin/fzf"]
  type = "archive-file"
  url = {{ gitHubLatestReleaseAssetURL "junegunn/fzf" (print "fzf-*_%s_%s.tar.gz" .chezmoi.os .chezmoi.arch) }}
  refresh = "168h"
  path = "fzf"

[".local/bin/delta"]
  type = "archive-file"
  url = {{ gitHubLatestReleaseAssetURL "dandavison/delta"  "delta-*-aarch64-unknown-linux-gnu.tar.gz" }}
  refresh = "168h"
  path = "delta"

[".local/bin/fastfetch"]
  type = "archive-file"
  url = {{ gitHubLatestReleaseAssetURL "fastfetch-cli/fastfetch" (printf "fastfetch-%s-%s.tar.gz" .chezmoi.os .chezmoi.arch) }}
  refresh = "168h"
  path = "fastfetch"
{{- end }}
