--- Galet colours generated by matugen from the wallpaper; shapes from galet-dark.
local theme = dofile(os.getenv("HOME") .. "/.config/themes/galet-dark/hyprland.lua")

local primary = "rgba({{colors.primary.default.hex_stripped}}ff)"
local dim = "rgba({{colors.outline_variant.default.hex_stripped}}ff)"
local gradient = {
	colors = {
		primary,
		"rgba({{colors.tertiary.default.hex_stripped}}ff)",
		"rgba({{colors.secondary.default.hex_stripped}}ff)",
		primary,
	},
	angle = 45,
}

theme.general.col = { active_border = gradient, inactive_border = dim }
theme.group.col = { border_active = gradient, border_inactive = dim }
theme.group.groupbar.col = { active = primary, inactive = dim }

return theme
