{{- /*
  vim:ft=toml.gotmpl:
*/ -}}
{{ if .isUbuntu }}
{{ $nerdFontsVersion := (gitHubLatestRelease "ryanoasis/nerd-fonts").TagName }}
[{{ .fontsDir | quote }}]
  type = "file"
  url = "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ $nerdFontsVersion }}/patched-fonts/FiraCode/Regular/FiraCodeNerdFontMono-Regular.ttf"
{{ end }}


{{ if .isWsl }}
{{ $externalScriptsDir := includeTemplate "get-external-scripts-dir" . }}
{{ $psScriptVersion := (gitHubLatestTag "ralish/PSWinGlue").Name }}
["{{ $externalScriptsDir }}/Install-Font.ps1"]
  type = "file"
  url = "https://raw.githubusercontent.com/ralish/PSWinGlue/{{ $psScriptVersion }}/Scripts/Install-Font.ps1"

["{{ $externalScriptsDir }}/Uninstall-Font.ps1"]
  type = "file"
  url = "https://raw.githubusercontent.com/ralish/PSWinGlue/{{ $psScriptVersion }}/Scripts/Uninstall-Font.ps1"
{{ end }}
