{{- /*
  vim:ft=toml.gotmpl:
*/ -}}

{{ if .isUbuntu }}
{{ $nerdFontsVersion := (gitHubLatestRelease "ryanoasis/nerd-fonts").TagName }}
{{ range .ubuntuFonts }}
{{ $fontName := . }}

["{{ joinPath ($.fontsDir) ($fontName) }}"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ $nerdFontsVersion }}/{{ $fontName }}.zip"
  urls = ["https://github.com/ryanoasis/nerd-fonts/releases/download/{{ $nerdFontsVersion }}/{{ $fontName }}.tar.xz"]
  refreshPeriod = "168h"
  include = [ "**/*.ttf" ]
{{ end }}
{{ end }}

{{ if .isWsl }}
{{ $externalScriptsDir := includeTemplate "get-external-scripts-dir" . }}
{{ $psScriptVersion := (gitHubLatestTag "ralish/PSWinGlue").Name }}
["{{ $externalScriptsDir }}/Install-Font.ps1"]
  type = "file"
  url = "https://raw.githubusercontent.com/ralish/PSWinGlue/{{ $psScriptVersion }}/Scripts/Install-Font.ps1"

["{{ $externalScriptsDir }}/Uninstall-Font.ps1"]
  type = "file"
  url = "https://raw.githubusercontent.com/ralish/PSWinGlue/{{ $psScriptVersion }}/Scripts/Uninstall-Font.ps1"
{{ end }}
